services:
  redis:
    image: "redis/redis-stack:latest"
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    environment:
      - REDIS_ARGS=--requirepass test --appendonly yes
    restart: always