spring:
  application:
    name: real-estate-be
  ai:
    openai:
      chat:
        base-url: ${OPENAI_BASE_URL}
        api-key: ${OPENAI_API_KEY}
        options:
          model: gpt-4o
      base-url: ${OPENAI_BASE_URL}
      api-key: ${OPENAI_API_KEY}
logging:
  level:
    org:
      springframework:
        web: DEBUG
        ai: DEBUG
