spring:
  application:
    name: real-estate-be
  ai:
    openai:
      chat:
        base-url: https://api.openai.com
        api-key: ${OPENAI_API_KEY}
        options:
          model: gpt-4o
      base-url: https://api.openai.com
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-nomic-embed-text-v2-moe
          dimensions: 768
logging:
  level:
    org:
      springframework:
        web: DEBUG
        ai: DEBUG
